name: tree_structs
description: A dart library for working with tree structures. This package allows you to create, manipulate, and traverse trees.
version: 1.0.8
repository: https://github.com/Mobile-Artificial-Intelligence/trees

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
