name: tree_structs
description: A dart library for working with tree structures.
version: 1.0.6
repository: https://github.com/danemadsen/trees

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
