name: tree_structs
description: A dart library for working with tree structures.
version: 1.0.4
repository: https://github.com/danemadsen/trees

environment:
  sdk: ^3.6.1

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
